spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://138.2.62.193:3306/project_db
    username : maroonest
    password : Vkfkrhs8985!
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    livereload:
      enabled: true
  logging:
    level:
      com.zaxxer.hikari: TRACE
      com.zaxxer.hikari.HikariConfig : DEBUG
      org.springframework.web.cors.DefaultCorsProcessor: TRACE
server:
  port: 9091
---